# Generated by Django 2.1.5 on 2020-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('spec', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('new', models.BooleanField(default=False)),
            ],
        ),
    ]
